version: '2'
services:
  datastore:
    image: busybox
    volumes:
      - mysql-data:/var/lib/mysql
      - bundle:/bundle
      - .:/app
  mysql:
    build: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes_from:
      - datastore
    networks:
      - default 
  app:
    build: ruby
    environment:
      - SAMPLE_DOCKER_DB_HOST=mysql
    volumes:
      - ./../:/app
    volumes_from:
      - datastore
    networks:
      - default 
    ports: 
      - "3088:3088"
    command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0", "-p", "3088"]
    tty: true
    links:
      - mysql 
    depends_on:
      - mysql

volumes:
  mysql-data:
    driver: local
  bundle:
    driver: local
