default: &default
  adapter: mysql2
  encoding: utf8mb4

development:
  <<: *default
  database: rspec_training_development
  username: root
  password: ~
  host: <%= ENV['SAMPLE_DOCKER_DB_HOST'] || '127.0.0.1' %>

test:
  <<: *default
  database: rspec_training_test
  username: root
  password: ~
  host: <%= ENV['SAMPLE_DOCKER_DB_HOST'] || '127.0.0.1' %>

production:
  <<: *default
  database: rspec_training_production
